version: '3.9'

services:

  admin:
    image: 'admin-service'
    build:
      dockerfile: ../admin/Dockerfile
    container_name: admin
    ports:
      - 8081:8081
    depends_on:
      - db
      - localstack
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/library_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: on-failure

  user:
    image: 'user-service'
    build:
      dockerfile: ../user/Dockerfile
    container_name: user
    ports:
      - 8082:8082
    depends_on:
      - db
      - localstack
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/library_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: on-failure

  localstack:
    image: localstack/localstack:0.12.9.1
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack:/tmp/localstack
    ports:
      - 4566:4566

  db:
    image: 'postgres'
    container_name: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cinema_db
      POSTGRES_INITDB_ARGS: -A md5
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all