spring:
  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false
  datasource:
    url: jdbc:postgresql://localhost:5432/movies_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 1000000MB
      max-request-size: 10000000MB
server:
  port: 8080
  tomcat:
    relaxed-query-chars:   <, > ,[ ,\, ] ,^ ,`, {, |, }
aws:
  s3-bucket: bucket
  localstack-url: http://${LOCALSTACK_URL:localhost}:4566

